global:
  scrape_interval: 5s  # Intervalo de coleta de métricas

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Substitua pelo seu endereço
