name: CI Pipeline

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # ou a versão que você está usando

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build  # se você tiver um script de build

    - name: Run linters
      run: npm run lint  # se você tiver um script de lint
